server:
  port: 8080
  address: 0.0.0.0

lavalink:
  server:
    password: "baotoxic"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingTimeoutMs: 1000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateIntervalMs: 1000
    gc-warnings: true

metrics:
  prometheus: false

suggesters:
  youtube: true
  spotify: false
  deezer: false
  applemusic: false

spotify:
  clientId: "38d04ede941546e880cf92b091e13329" # Điền Spotify Client ID của bạn nếu bạn muốn hỗ trợ Spotify
  clientSecret: "902de3f31e0745b285a9a1550ea476c9" # Điền Spotify Client Secret của bạn
